Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/07/2025
Var
// Seção de Declarações das variáveis 
p, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
p <- 1
escreva(p)
i <- 0
enquanto p < 1000 faca
         p <- p + i
         se p < 1000 entao
            escreva(p)
         fimse
         i <- i + 1
fimenquanto


Fimalgoritmo