Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/06/2025
Var
// Seção de Declarações das variáveis 
f : inteiro
c : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
f <- 50
enquanto f <= 150 faca
         c <- 5/9 * (f - 32)
         escreva(f, c)
         f <- f + 1
fimenquanto


Fimalgoritmo