Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/07/2025
Var
// Seção de Declarações das variáveis 
h, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
h <- 7
escreva(h)
i <- 2
enquanto i <= 32 faca
         h <- 3 * h + 2
         escreva(h)
         i <- i + 1
fimenquanto


Fimalgoritmo