Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/07/2025
Var
// Seção de Declarações das variáveis 
n : inteiro
v : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
v <- 65536
escreva(v)
n <- 2
enquanto n <= 17 faca
         v <- v / 2
         escreva(v)
         n <- n + 1
fimenquanto

         

Fimalgoritmo