Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/07/2025
Var
// Seção de Declarações das variáveis 
d, s : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
d <- 1
s <- d
enquanto abs(d) >= 1/10000000000 faca
         d <- d/2 * - 1
         s <- s + d
fimenquanto
escreva(s)

Fimalgoritmo