Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/07/2025
Var
// Seção de Declarações das variáveis 
r : real
n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
r <- 1
n <- 1
enquanto r >= 0.00000000000000000001 faca
         r <- r / 2
         n <- n + 1
fimenquanto
escreva("Essa sequencia tem ", n, " numeros.")

Fimalgoritmo